# Generated by Django 3.1.5 on 2021-01-27 09:28

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import schema.constants
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schema',
            name='column_separator',
            field=models.CharField(choices=[(',', 'Comma'), (';', 'Semicolon'), ('\\t', 'Tab'), ('|', 'Pipe')], max_length=2),
        ),
        migrations.CreateModel(
            name='GenerationTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[(0, 'New'), (1, 'Processing'), (2, 'Ready')], default=schema.constants.TaskStatus['NEW'], max_length=15)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('schema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='schema.schema')),
            ],
        ),
    ]
