# Generated by Django 3.1.5 on 2021-01-27 09:29

from django.db import migrations, models
import schema.constants


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0002_auto_20210127_0928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='generationtask',
            name='status',
            field=models.CharField(choices=[(0, 'New'), (1, 'Processing'),
                                            (2, 'Ready'), (3, 'Failed')],
                                   default=schema.constants.TaskStatus['NEW'],
                                   max_length=15),
        ),
    ]
