# Generated by Django 3.1.5 on 2021-01-27 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('schema', '0003_auto_20210127_0929'),
    ]

    operations = [
        migrations.AddField(
            model_name='generationtask',
            name='row_number',
            field=models.IntegerField(),
        ),
    ]
